version: '1.0.{build}'

image: Visual Studio 2017

install:
    - git submodule update --init --recursive

before_build:
    - cmake -DBUILD_TESTS=True -DBUILD_EXAMPLES=True .

build:
    project: $(APPVEYOR_BUILD_FOLDER)\gdcpp.sln

test_script:
    - '%APPVEYOR_BUILD_FOLDER%\Debug\test\run_tests.exe'
